from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_OperatorForm(object):

    def calcMetalChargeClicked(self):
        try:
            self.calcMetalCharge.clicked.connect(self.calcMetalChargeClicked())
            steelCarbonValue = float(self.steelCarbon.text())
            steelSerumValue = float(self.steelSerum.text())
            steelSiliconValue = float(self.steelSilicon.text())
            steelPhosphorValue = float(self.scrapPhosphor.text())

            castSteelWeightValue = float(self.castWeight.text())
            castSteelTemperatureValue = float(self.castTemperature.text())
            castSteelCarbonValue = float(self.castCarbon.text())
            castSteelSerumValue = float(self.castSerum.text())
            castSteelSiliconValue = float(self.castSilicon.text())
            castSteelPhosphorValue = float(self.castPhosphor.text())
            castSteelManganeseValue = float(self.castManganese.text())

            scrapCarbonValue = float(self.scrapCarbon.text())
            scrapSerumValue = float(self.scrapSerum.text())
            scrapSiliconValue = float(self.scrapSilicon.text())
            scrapPhosphorValue = float(self.scrapPhosphor.text())
            scrapWeightValue = float(self.scrapWeight.text())
            scrapManganeseValue = float(self.scrapPhosphor.text())

            totalWeightValue = castSteelWeightValue + scrapWeightValue
            self.MetalCharge = totalWeightValue
            self.ChemCarbon = (castSteelCarbonValue * castSteelWeightValue + scrapCarbonValue * scrapWeightValue)/totalWeightValue
            self.ChemSerum = (castSteelSerumValue * castSteelWeightValue + scrapSerumValue * scrapWeightValue)/totalWeightValue
            self.ChemPhosphor = (castSteelPhosphorValue * castSteelWeightValue + scrapPhosphorValue * scrapWeightValue)/totalWeightValue
            self.ChemSilicon = (castSteelSiliconValue * castSteelWeightValue + scrapSiliconValue * scrapWeightValue)/totalWeightValue
            self.ChemManganese = (castSteelManganeseValue * castSteelWeightValue + scrapManganeseValue * scrapWeightValue)/totalWeightValue

        except Exception as err:  # mc.Error
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setWindowTitle("Ошибка")
            msg.setText("Внимание")
            msg.setInformativeText("Проверьте введенные данные! {0}".format(err))
            # msg.setInformativeText("Error: {0}".format(err))
            msg.exec_()
        return

    def setupUi(self, OperatorForm):
        OperatorForm.setObjectName("OperatorForm")
        OperatorForm.resize(993, 670)
        self.centralwidget = QtWidgets.QWidget(OperatorForm)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 981, 731))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 301, 111))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 281, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(150, 20, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(150, 50, 61, 16))
        self.label_4.setObjectName("label_4")
        self.steelCarbon = QtWidgets.QLineEdit(self.groupBox_4)
        self.steelCarbon.setGeometry(QtCore.QRect(80, 20, 51, 20))
        self.steelCarbon.setObjectName("steelCarbon")
        self.steelSilicon = QtWidgets.QLineEdit(self.groupBox_4)
        self.steelSilicon.setGeometry(QtCore.QRect(80, 50, 51, 20))
        self.steelSilicon.setObjectName("steelSilicon")
        self.steelSerum = QtWidgets.QLineEdit(self.groupBox_4)
        self.steelSerum.setGeometry(QtCore.QRect(220, 20, 51, 20))
        self.steelSerum.setObjectName("steelSerum")
        self.steelPhosphor = QtWidgets.QLineEdit(self.groupBox_4)
        self.steelPhosphor.setGeometry(QtCore.QRect(220, 50, 51, 20))
        self.steelPhosphor.setObjectName("steelPhosphor")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 10, 301, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.castTemperature = QtWidgets.QLineEdit(self.groupBox_2)
        self.castTemperature.setGeometry(QtCore.QRect(110, 20, 81, 20))
        self.castTemperature.setText("")
        self.castTemperature.setObjectName("castTemperature")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_6.setObjectName("label_6")
        self.castWeight = QtWidgets.QLineEdit(self.groupBox_2)
        self.castWeight.setGeometry(QtCore.QRect(110, 50, 81, 20))
        self.castWeight.setText("")
        self.castWeight.setObjectName("castWeight")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 70, 281, 111))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(150, 20, 51, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(150, 50, 61, 16))
        self.label_10.setObjectName("label_10")
        self.castCarbon = QtWidgets.QLineEdit(self.groupBox_6)
        self.castCarbon.setGeometry(QtCore.QRect(80, 20, 51, 20))
        self.castCarbon.setObjectName("castCarbon")
        self.castSilicon = QtWidgets.QLineEdit(self.groupBox_6)
        self.castSilicon.setGeometry(QtCore.QRect(80, 50, 51, 20))
        self.castSilicon.setObjectName("castSilicon")
        self.castSerum = QtWidgets.QLineEdit(self.groupBox_6)
        self.castSerum.setGeometry(QtCore.QRect(220, 20, 51, 20))
        self.castSerum.setObjectName("castSerum")
        self.castPhosphor = QtWidgets.QLineEdit(self.groupBox_6)
        self.castPhosphor.setGeometry(QtCore.QRect(220, 50, 51, 20))
        self.castPhosphor.setObjectName("castPhosphor")
        self.castManganese = QtWidgets.QLineEdit(self.groupBox_6)
        self.castManganese.setEnabled(True)
        self.castManganese.setGeometry(QtCore.QRect(220, 80, 51, 20))
        self.castManganese.setText("")
        self.castManganese.setObjectName("castManganese")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(130, 80, 81, 16))
        self.label_24.setObjectName("label_24")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 220, 301, 80))
        self.groupBox_5.setObjectName("groupBox_5")
        self.MetalCharge = QtWidgets.QLineEdit(self.groupBox_5)
        self.MetalCharge.setEnabled(False)
        self.MetalCharge.setGeometry(QtCore.QRect(60, 30, 51, 20))
        self.MetalCharge.setObjectName("MetalCharge")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_16.setObjectName("label_16")
        self.calcMetalCharge = QtWidgets.QPushButton(self.groupBox_5)
        self.calcMetalCharge.setEnabled(True)
        self.calcMetalCharge.setGeometry(QtCore.QRect(240, 10, 51, 61))
        self.calcMetalCharge.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("SteelmakingConverter/GUI\\../Pictures/calculate.ico"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.calcMetalCharge.setIcon(icon)
        self.calcMetalCharge.setIconSize(QtCore.QSize(48, 48))
        self.calcMetalCharge.setObjectName("calcMetalCharge")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(640, 10, 301, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_11.setObjectName("label_11")
        self.scrapWeight = QtWidgets.QLineEdit(self.groupBox_3)
        self.scrapWeight.setGeometry(QtCore.QRect(70, 30, 81, 20))
        self.scrapWeight.setText("")
        self.scrapWeight.setObjectName("scrapWeight")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 70, 281, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(150, 20, 51, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(150, 50, 61, 16))
        self.label_15.setObjectName("label_15")
        self.scrapCarbon = QtWidgets.QLineEdit(self.groupBox_7)
        self.scrapCarbon.setGeometry(QtCore.QRect(80, 20, 51, 20))
        self.scrapCarbon.setObjectName("scrapCarbon")
        self.scrapSilicon = QtWidgets.QLineEdit(self.groupBox_7)
        self.scrapSilicon.setGeometry(QtCore.QRect(80, 50, 51, 20))
        self.scrapSilicon.setObjectName("scrapSilicon")
        self.scrapSerum = QtWidgets.QLineEdit(self.groupBox_7)
        self.scrapSerum.setGeometry(QtCore.QRect(220, 20, 51, 20))
        self.scrapSerum.setObjectName("scrapSerum")
        self.scrapPhosphor = QtWidgets.QLineEdit(self.groupBox_7)
        self.scrapPhosphor.setGeometry(QtCore.QRect(220, 50, 51, 20))
        self.scrapPhosphor.setObjectName("scrapPhosphor")
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(130, 80, 81, 16))
        self.label_25.setObjectName("label_25")
        self.scrapManganese = QtWidgets.QLineEdit(self.groupBox_7)
        self.scrapManganese.setEnabled(True)
        self.scrapManganese.setGeometry(QtCore.QRect(220, 80, 51, 20))
        self.scrapManganese.setText("")
        self.scrapManganese.setObjectName("scrapManganese")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(330, 220, 471, 80))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_17.setObjectName("label_17")
        self.ChemCarbon = QtWidgets.QLineEdit(self.groupBox_8)
        self.ChemCarbon.setEnabled(False)
        self.ChemCarbon.setGeometry(QtCore.QRect(80, 20, 51, 20))
        self.ChemCarbon.setObjectName("ChemCarbon")
        self.label_18 = QtWidgets.QLabel(self.groupBox_8)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label_18.setObjectName("label_18")
        self.ChemSerum = QtWidgets.QLineEdit(self.groupBox_8)
        self.ChemSerum.setEnabled(False)
        self.ChemSerum.setGeometry(QtCore.QRect(80, 50, 51, 20))
        self.ChemSerum.setObjectName("ChemSerum")
        self.ChemSilicon = QtWidgets.QLineEdit(self.groupBox_8)
        self.ChemSilicon.setEnabled(False)
        self.ChemSilicon.setGeometry(QtCore.QRect(210, 20, 51, 20))
        self.ChemSilicon.setObjectName("ChemSilicon")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(140, 20, 71, 16))
        self.label_19.setObjectName("label_19")
        self.ChemPhosphor = QtWidgets.QLineEdit(self.groupBox_8)
        self.ChemPhosphor.setEnabled(False)
        self.ChemPhosphor.setGeometry(QtCore.QRect(210, 50, 51, 20))
        self.ChemPhosphor.setObjectName("ChemPhosphor")
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setGeometry(QtCore.QRect(140, 50, 61, 16))
        self.label_20.setObjectName("label_20")
        self.ChemManganese = QtWidgets.QLineEdit(self.groupBox_8)
        self.ChemManganese.setEnabled(False)
        self.ChemManganese.setGeometry(QtCore.QRect(350, 20, 51, 20))
        self.ChemManganese.setText("")
        self.ChemManganese.setObjectName("ChemManganese")
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(270, 20, 91, 16))
        self.label_21.setObjectName("label_21")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 310, 901, 281))
        self.groupBox_9.setObjectName("groupBox_9")
        self.MetalCharge_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.MetalCharge_2.setEnabled(False)
        self.MetalCharge_2.setGeometry(QtCore.QRect(70, 30, 71, 20))
        self.MetalCharge_2.setObjectName("MetalCharge_2")
        self.label_22 = QtWidgets.QLabel(self.groupBox_9)
        self.label_22.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_22.setObjectName("label_22")
        self.OxidationTable = QtWidgets.QTableWidget(self.groupBox_9)
        self.OxidationTable.setEnabled(False)
        self.OxidationTable.setGeometry(QtCore.QRect(10, 60, 811, 211))
        self.OxidationTable.setObjectName("OxidationTable")
        self.OxidationTable.setColumnCount(8)
        self.OxidationTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.OxidationTable.setItem(0, 0, item)
        self.OxidationTable.horizontalHeader().setDefaultSectionSize(80)
        self.calcTable = QtWidgets.QPushButton(self.groupBox_9)
        self.calcTable.setEnabled(True)
        self.calcTable.setGeometry(QtCore.QRect(830, 60, 51, 61))
        self.calcTable.setText("")
        self.calcTable.setIcon(icon)
        self.calcTable.setIconSize(QtCore.QSize(48, 48))
        self.calcTable.setObjectName("calcTable")
        self.NextSlag = QtWidgets.QLabel(self.tab)
        self.NextSlag.setEnabled(False)
        self.NextSlag.setGeometry(QtCore.QRect(940, 530, 61, 61))
        self.NextSlag.setText("")
        self.NextSlag.setPixmap(QtGui.QPixmap(":/icons/icons/arrow_right.ico"))
        self.NextSlag.setScaledContents(True)
        self.NextSlag.setObjectName("NextSlag")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 10, 301, 80))
        self.groupBox_11.setObjectName("groupBox_11")
        self.ModeComboBox = QtWidgets.QComboBox(self.groupBox_11)
        self.ModeComboBox.setGeometry(QtCore.QRect(70, 30, 141, 22))
        self.ModeComboBox.setObjectName("ModeComboBox")
        self.label_23 = QtWidgets.QLabel(self.groupBox_11)
        self.label_23.setGeometry(QtCore.QRect(10, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.AddNewMode = QtWidgets.QPushButton(self.groupBox_11)
        self.AddNewMode.setEnabled(False)
        self.AddNewMode.setGeometry(QtCore.QRect(260, 50, 31, 21))
        self.AddNewMode.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("SteelmakingConverter/GUI\\../Pictures/add.ico"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.AddNewMode.setIcon(icon1)
        self.AddNewMode.setObjectName("AddNewMode")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 10, 231, 251))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.FluxeTable = QtWidgets.QTableWidget(self.groupBox_10)
        self.FluxeTable.setGeometry(QtCore.QRect(10, 60, 211, 151))
        self.FluxeTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.FluxeTable.setObjectName("FluxeTable")
        self.FluxeTable.setColumnCount(2)
        self.FluxeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.FluxeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.FluxeTable.setHorizontalHeaderItem(1, item)
        self.AddFluxeButton = QtWidgets.QPushButton(self.groupBox_10)
        self.AddFluxeButton.setGeometry(QtCore.QRect(160, 220, 31, 21))
        self.AddFluxeButton.setText("")
        self.AddFluxeButton.setIcon(icon1)
        self.AddFluxeButton.setObjectName("AddFluxeButton")
        self.tip_flyusa_label = QtWidgets.QLabel(self.groupBox_10)
        self.tip_flyusa_label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.tip_flyusa_label.setObjectName("tip_flyusa_label")
        self.FluxeType = QtWidgets.QComboBox(self.groupBox_10)
        self.FluxeType.setGeometry(QtCore.QRect(80, 30, 141, 22))
        self.FluxeType.setEditable(False)
        self.FluxeType.setObjectName("FluxeType")
        self.RemoveFluxeButton = QtWidgets.QPushButton(self.groupBox_10)
        self.RemoveFluxeButton.setGeometry(QtCore.QRect(190, 220, 31, 21))
        self.RemoveFluxeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("SteelmakingConverter/GUI\\../Pictures/remove.ico"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.RemoveFluxeButton.setIcon(icon2)
        self.RemoveFluxeButton.setObjectName("RemoveFluxeButton")
        self.shlak_group_box = QtWidgets.QGroupBox(self.tab_2)
        self.shlak_group_box.setGeometry(QtCore.QRect(260, 20, 651, 241))
        self.shlak_group_box.setObjectName("shlak_group_box")
        self.him_sostav_shlaka_group_box = QtWidgets.QGroupBox(self.shlak_group_box)
        self.him_sostav_shlaka_group_box.setGeometry(QtCore.QRect(10, 70, 311, 161))
        self.him_sostav_shlaka_group_box.setObjectName("him_sostav_shlaka_group_box")
        self.SlagSiO2Label = QtWidgets.QLabel(self.him_sostav_shlaka_group_box)
        self.SlagSiO2Label.setGeometry(QtCore.QRect(10, 30, 46, 13))
        self.SlagSiO2Label.setObjectName("SlagSiO2Label")
        self.SlagCaOLabel = QtWidgets.QLabel(self.him_sostav_shlaka_group_box)
        self.SlagCaOLabel.setGeometry(QtCore.QRect(10, 60, 46, 13))
        self.SlagCaOLabel.setObjectName("SlagCaOLabel")
        self.SlagMgOLabel = QtWidgets.QLabel(self.him_sostav_shlaka_group_box)
        self.SlagMgOLabel.setGeometry(QtCore.QRect(10, 90, 46, 13))
        self.SlagMgOLabel.setObjectName("SlagMgOLabel")
        self.SlagAl2O3Label = QtWidgets.QLabel(self.him_sostav_shlaka_group_box)
        self.SlagAl2O3Label.setGeometry(QtCore.QRect(170, 30, 46, 13))
        self.SlagAl2O3Label.setObjectName("SlagAl2O3Label")
        self.SlagOthersLabel = QtWidgets.QLabel(self.him_sostav_shlaka_group_box)
        self.SlagOthersLabel.setGeometry(QtCore.QRect(10, 120, 46, 13))
        self.SlagOthersLabel.setObjectName("SlagOthersLabel")
        self.SlagSiO2 = QtWidgets.QLineEdit(self.him_sostav_shlaka_group_box)
        self.SlagSiO2.setEnabled(False)
        self.SlagSiO2.setGeometry(QtCore.QRect(60, 30, 91, 20))
        self.SlagSiO2.setInputMask("")
        self.SlagSiO2.setObjectName("SlagSiO2")
        self.SlagCaO = QtWidgets.QLineEdit(self.him_sostav_shlaka_group_box)
        self.SlagCaO.setEnabled(False)
        self.SlagCaO.setGeometry(QtCore.QRect(60, 60, 91, 20))
        self.SlagCaO.setInputMask("")
        self.SlagCaO.setObjectName("SlagCaO")
        self.SlagMgO = QtWidgets.QLineEdit(self.him_sostav_shlaka_group_box)
        self.SlagMgO.setEnabled(False)
        self.SlagMgO.setGeometry(QtCore.QRect(60, 90, 91, 20))
        self.SlagMgO.setInputMask("")
        self.SlagMgO.setObjectName("SlagMgO")
        self.SlagAl2O3 = QtWidgets.QLineEdit(self.him_sostav_shlaka_group_box)
        self.SlagAl2O3.setEnabled(False)
        self.SlagAl2O3.setGeometry(QtCore.QRect(210, 30, 91, 20))
        self.SlagAl2O3.setInputMask("")
        self.SlagAl2O3.setObjectName("SlagAl2O3")
        self.SlagOthers = QtWidgets.QLineEdit(self.him_sostav_shlaka_group_box)
        self.SlagOthers.setEnabled(False)
        self.SlagOthers.setGeometry(QtCore.QRect(60, 120, 91, 20))
        self.SlagOthers.setInputMask("")
        self.SlagOthers.setObjectName("SlagOthers")
        self.SlagFeO = QtWidgets.QLineEdit(self.him_sostav_shlaka_group_box)
        self.SlagFeO.setEnabled(False)
        self.SlagFeO.setGeometry(QtCore.QRect(210, 60, 91, 20))
        self.SlagFeO.setInputMask("")
        self.SlagFeO.setObjectName("SlagFeO")
        self.SlagFeOLabel = QtWidgets.QLabel(self.him_sostav_shlaka_group_box)
        self.SlagFeOLabel.setGeometry(QtCore.QRect(170, 60, 46, 13))
        self.SlagFeOLabel.setObjectName("SlagFeOLabel")
        self.SlagFe2O3 = QtWidgets.QLineEdit(self.him_sostav_shlaka_group_box)
        self.SlagFe2O3.setEnabled(False)
        self.SlagFe2O3.setGeometry(QtCore.QRect(210, 90, 91, 20))
        self.SlagFe2O3.setInputMask("")
        self.SlagFe2O3.setObjectName("SlagFe2O3")
        self.SlagFe2O3Label = QtWidgets.QLabel(self.him_sostav_shlaka_group_box)
        self.SlagFe2O3Label.setGeometry(QtCore.QRect(170, 90, 46, 13))
        self.SlagFe2O3Label.setObjectName("SlagFe2O3Label")
        self.SlagWeightLabel = QtWidgets.QLabel(self.shlak_group_box)
        self.SlagWeightLabel.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.SlagWeightLabel.setObjectName("SlagWeightLabel")
        self.SlagWeight = QtWidgets.QLineEdit(self.shlak_group_box)
        self.SlagWeight.setEnabled(False)
        self.SlagWeight.setGeometry(QtCore.QRect(80, 30, 121, 20))
        self.SlagWeight.setObjectName("SlagWeight")
        self.SlagCalc = QtWidgets.QPushButton(self.shlak_group_box)
        self.SlagCalc.setEnabled(True)
        self.SlagCalc.setGeometry(QtCore.QRect(590, 10, 51, 61))
        self.SlagCalc.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/calculate.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SlagCalc.setIcon(icon3)
        self.SlagCalc.setIconSize(QtCore.QSize(48, 48))
        self.SlagCalc.setObjectName("SlagCalc")
        self.him_sostav_shlaka_v_procentah_group_box = QtWidgets.QGroupBox(self.shlak_group_box)
        self.him_sostav_shlaka_v_procentah_group_box.setGeometry(QtCore.QRect(330, 70, 311, 161))
        self.him_sostav_shlaka_v_procentah_group_box.setObjectName("him_sostav_shlaka_v_procentah_group_box")
        self.SlagSiO2Perc = QtWidgets.QLineEdit(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagSiO2Perc.setEnabled(False)
        self.SlagSiO2Perc.setGeometry(QtCore.QRect(60, 30, 91, 20))
        self.SlagSiO2Perc.setInputMask("")
        self.SlagSiO2Perc.setObjectName("SlagSiO2Perc")
        self.SlagAl2O3Label_2 = QtWidgets.QLabel(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagAl2O3Label_2.setGeometry(QtCore.QRect(170, 30, 46, 13))
        self.SlagAl2O3Label_2.setObjectName("SlagAl2O3Label_2")
        self.SlagAl2O3Perc = QtWidgets.QLineEdit(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagAl2O3Perc.setEnabled(False)
        self.SlagAl2O3Perc.setGeometry(QtCore.QRect(210, 30, 91, 20))
        self.SlagAl2O3Perc.setInputMask("")
        self.SlagAl2O3Perc.setObjectName("SlagAl2O3Perc")
        self.SlagFeOPerc = QtWidgets.QLineEdit(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagFeOPerc.setEnabled(False)
        self.SlagFeOPerc.setGeometry(QtCore.QRect(210, 60, 91, 20))
        self.SlagFeOPerc.setInputMask("")
        self.SlagFeOPerc.setObjectName("SlagFeOPerc")
        self.SlagFeOLabel_2 = QtWidgets.QLabel(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagFeOLabel_2.setGeometry(QtCore.QRect(170, 60, 46, 13))
        self.SlagFeOLabel_2.setObjectName("SlagFeOLabel_2")
        self.SlagFe2O3Label_2 = QtWidgets.QLabel(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagFe2O3Label_2.setGeometry(QtCore.QRect(170, 90, 46, 13))
        self.SlagFe2O3Label_2.setObjectName("SlagFe2O3Label_2")
        self.SlagSiO2Label_2 = QtWidgets.QLabel(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagSiO2Label_2.setGeometry(QtCore.QRect(10, 30, 46, 13))
        self.SlagSiO2Label_2.setObjectName("SlagSiO2Label_2")
        self.SlagCaOPerc = QtWidgets.QLineEdit(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagCaOPerc.setEnabled(False)
        self.SlagCaOPerc.setGeometry(QtCore.QRect(60, 60, 91, 20))
        self.SlagCaOPerc.setInputMask("")
        self.SlagCaOPerc.setObjectName("SlagCaOPerc")
        self.SlagCaOLabel_2 = QtWidgets.QLabel(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagCaOLabel_2.setGeometry(QtCore.QRect(10, 60, 46, 13))
        self.SlagCaOLabel_2.setObjectName("SlagCaOLabel_2")
        self.SlagOthersPerc = QtWidgets.QLineEdit(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagOthersPerc.setEnabled(False)
        self.SlagOthersPerc.setGeometry(QtCore.QRect(60, 120, 91, 20))
        self.SlagOthersPerc.setInputMask("")
        self.SlagOthersPerc.setObjectName("SlagOthersPerc")
        self.SlagMgOPerc = QtWidgets.QLineEdit(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagMgOPerc.setEnabled(False)
        self.SlagMgOPerc.setGeometry(QtCore.QRect(60, 90, 91, 20))
        self.SlagMgOPerc.setInputMask("")
        self.SlagMgOPerc.setObjectName("SlagMgOPerc")
        self.SlagMgOLabel_2 = QtWidgets.QLabel(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagMgOLabel_2.setGeometry(QtCore.QRect(10, 90, 46, 13))
        self.SlagMgOLabel_2.setObjectName("SlagMgOLabel_2")
        self.SlagFe2O3Perc = QtWidgets.QLineEdit(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagFe2O3Perc.setEnabled(False)
        self.SlagFe2O3Perc.setGeometry(QtCore.QRect(210, 90, 91, 20))
        self.SlagFe2O3Perc.setInputMask("")
        self.SlagFe2O3Perc.setObjectName("SlagFe2O3Perc")
        self.SlagOthersLabel_2 = QtWidgets.QLabel(self.him_sostav_shlaka_v_procentah_group_box)
        self.SlagOthersLabel_2.setGeometry(QtCore.QRect(10, 120, 46, 13))
        self.SlagOthersLabel_2.setObjectName("SlagOthersLabel_2")
        self.raschet_dutya_group_box = QtWidgets.QGroupBox(self.tab_2)
        self.raschet_dutya_group_box.setGeometry(QtCore.QRect(20, 270, 371, 231))
        self.raschet_dutya_group_box.setObjectName("raschet_dutya_group_box")
        self.TotalConsumptionOfBlastKg = QtWidgets.QLineEdit(self.raschet_dutya_group_box)
        self.TotalConsumptionOfBlastKg.setEnabled(False)
        self.TotalConsumptionOfBlastKg.setGeometry(QtCore.QRect(260, 70, 91, 20))
        self.TotalConsumptionOfBlastKg.setObjectName("TotalConsumptionOfBlastKg")
        self.ExcessBlast = QtWidgets.QLineEdit(self.raschet_dutya_group_box)
        self.ExcessBlast.setEnabled(False)
        self.ExcessBlast.setGeometry(QtCore.QRect(260, 130, 91, 20))
        self.ExcessBlast.setObjectName("ExcessBlast")
        self.TotalConsumptionOfBlastM3 = QtWidgets.QLineEdit(self.raschet_dutya_group_box)
        self.TotalConsumptionOfBlastM3.setEnabled(False)
        self.TotalConsumptionOfBlastM3.setGeometry(QtCore.QRect(260, 100, 91, 20))
        self.TotalConsumptionOfBlastM3.setObjectName("TotalConsumptionOfBlastM3")
        self.TotalOxygenDemandBlast = QtWidgets.QLineEdit(self.raschet_dutya_group_box)
        self.TotalOxygenDemandBlast.setEnabled(False)
        self.TotalOxygenDemandBlast.setGeometry(QtCore.QRect(260, 40, 91, 20))
        self.TotalOxygenDemandBlast.setObjectName("TotalOxygenDemandBlast")
        self.TotalOxygenDemandBlastLabel = QtWidgets.QLabel(self.raschet_dutya_group_box)
        self.TotalOxygenDemandBlastLabel.setGeometry(QtCore.QRect(20, 40, 231, 16))
        self.TotalOxygenDemandBlastLabel.setObjectName("TotalOxygenDemandBlastLabel")
        self.TotalConsumptionOfBlastKgLabel = QtWidgets.QLabel(self.raschet_dutya_group_box)
        self.TotalConsumptionOfBlastKgLabel.setGeometry(QtCore.QRect(20, 70, 191, 16))
        self.TotalConsumptionOfBlastKgLabel.setObjectName("TotalConsumptionOfBlastKgLabel")
        self.ExcessBlastLabel = QtWidgets.QLabel(self.raschet_dutya_group_box)
        self.ExcessBlastLabel.setGeometry(QtCore.QRect(20, 130, 201, 16))
        self.ExcessBlastLabel.setObjectName("ExcessBlastLabel")
        self.TotalConsumptionOfBlastM3Label = QtWidgets.QLabel(self.raschet_dutya_group_box)
        self.TotalConsumptionOfBlastM3Label.setGeometry(QtCore.QRect(20, 100, 191, 16))
        self.TotalConsumptionOfBlastM3Label.setObjectName("TotalConsumptionOfBlastM3Label")
        self.BlastCalc = QtWidgets.QPushButton(self.raschet_dutya_group_box)
        self.BlastCalc.setEnabled(True)
        self.BlastCalc.setGeometry(QtCore.QRect(300, 160, 51, 61))
        self.BlastCalc.setText("")
        self.BlastCalc.setIcon(icon)
        self.BlastCalc.setIconSize(QtCore.QSize(48, 48))
        self.BlastCalc.setObjectName("BlastCalc")
        self.NextMat = QtWidgets.QLabel(self.tab_2)
        self.NextMat.setEnabled(False)
        self.NextMat.setGeometry(QtCore.QRect(940, 540, 61, 61))
        self.NextMat.setText("")
        self.NextMat.setPixmap(QtGui.QPixmap(":/icons/icons/arrow_right.ico"))
        self.NextMat.setScaledContents(True)
        self.NextMat.setObjectName("NextMat")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.ReclaimedIronWeightLabel = QtWidgets.QLabel(self.tab_3)
        self.ReclaimedIronWeightLabel.setGeometry(QtCore.QRect(10, 20, 371, 21))
        self.ReclaimedIronWeightLabel.setLineWidth(0)
        self.ReclaimedIronWeightLabel.setObjectName("ReclaimedIronWeightLabel")
        self.ReclaimedIronWeight = QtWidgets.QLineEdit(self.tab_3)
        self.ReclaimedIronWeight.setEnabled(False)
        self.ReclaimedIronWeight.setGeometry(QtCore.QRect(380, 20, 81, 20))
        self.ReclaimedIronWeight.setObjectName("ReclaimedIronWeight")
        self.prihodnie_dannye_table_widget = QtWidgets.QTableWidget(self.tab_3)
        self.prihodnie_dannye_table_widget.setEnabled(False)
        self.prihodnie_dannye_table_widget.setGeometry(QtCore.QRect(10, 90, 211, 361))
        self.prihodnie_dannye_table_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prihodnie_dannye_table_widget.setObjectName("prihodnie_dannye_table_widget")
        self.prihodnie_dannye_table_widget.setColumnCount(2)
        self.prihodnie_dannye_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_dannye_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_dannye_table_widget.setHorizontalHeaderItem(1, item)
        self.rashodnie_dannye_table_widget = QtWidgets.QTableWidget(self.tab_3)
        self.rashodnie_dannye_table_widget.setEnabled(False)
        self.rashodnie_dannye_table_widget.setGeometry(QtCore.QRect(250, 90, 211, 361))
        self.rashodnie_dannye_table_widget.setObjectName("rashodnie_dannye_table_widget")
        self.rashodnie_dannye_table_widget.setColumnCount(2)
        self.rashodnie_dannye_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_dannye_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_dannye_table_widget.setHorizontalHeaderItem(1, item)
        self.vyhod_zhidkovo_metalla_pered_raskisleniem_line_edit = QtWidgets.QLineEdit(self.tab_3)
        self.vyhod_zhidkovo_metalla_pered_raskisleniem_line_edit.setEnabled(False)
        self.vyhod_zhidkovo_metalla_pered_raskisleniem_line_edit.setGeometry(QtCore.QRect(380, 50, 81, 20))
        self.vyhod_zhidkovo_metalla_pered_raskisleniem_line_edit.setObjectName(
            "vyhod_zhidkovo_metalla_pered_raskisleniem_line_edit")
        self.vyhod_zhidkovo_metalla_pered_raskisleniem_label = QtWidgets.QLabel(self.tab_3)
        self.vyhod_zhidkovo_metalla_pered_raskisleniem_label.setGeometry(QtCore.QRect(10, 50, 311, 16))
        self.vyhod_zhidkovo_metalla_pered_raskisleniem_label.setObjectName(
            "vyhod_zhidkovo_metalla_pered_raskisleniem_label")
        self.rashodnaya_chast_group_box = QtWidgets.QGroupBox(self.tab_3)
        self.rashodnaya_chast_group_box.setGeometry(QtCore.QRect(470, 80, 471, 371))
        self.rashodnaya_chast_group_box.setObjectName("rashodnaya_chast_group_box")
        self.massa_okislivshihsya_primesei_label = QtWidgets.QLabel(self.rashodnaya_chast_group_box)
        self.massa_okislivshihsya_primesei_label.setGeometry(QtCore.QRect(20, 30, 181, 16))
        self.massa_okislivshihsya_primesei_label.setObjectName("massa_okislivshihsya_primesei_label")
        self.massa_oksidov_zheleza_label = QtWidgets.QLabel(self.rashodnaya_chast_group_box)
        self.massa_oksidov_zheleza_label.setGeometry(QtCore.QRect(20, 50, 251, 16))
        self.massa_oksidov_zheleza_label.setObjectName("massa_oksidov_zheleza_label")
        self.poteri_metalla_s_vynosami_i_vybrosami_label = QtWidgets.QLabel(self.rashodnaya_chast_group_box)
        self.poteri_metalla_s_vynosami_i_vybrosami_label.setGeometry(QtCore.QRect(20, 70, 251, 16))
        self.poteri_metalla_s_vynosami_i_vybrosami_label.setObjectName("poteri_metalla_s_vynosami_i_vybrosami_label")
        self.poteri_zheleza_s_pylyu_label = QtWidgets.QLabel(self.rashodnaya_chast_group_box)
        self.poteri_zheleza_s_pylyu_label.setGeometry(QtCore.QRect(20, 90, 251, 16))
        self.poteri_zheleza_s_pylyu_label.setObjectName("poteri_zheleza_s_pylyu_label")
        self.massa_okislivshihsya_primesei_line_edit = QtWidgets.QLineEdit(self.rashodnaya_chast_group_box)
        self.massa_okislivshihsya_primesei_line_edit.setEnabled(False)
        self.massa_okislivshihsya_primesei_line_edit.setGeometry(QtCore.QRect(270, 30, 101, 20))
        self.massa_okislivshihsya_primesei_line_edit.setObjectName("massa_okislivshihsya_primesei_line_edit")
        self.massa_oksidov_zheleza_line_edit = QtWidgets.QLineEdit(self.rashodnaya_chast_group_box)
        self.massa_oksidov_zheleza_line_edit.setEnabled(False)
        self.massa_oksidov_zheleza_line_edit.setGeometry(QtCore.QRect(270, 50, 101, 20))
        self.massa_oksidov_zheleza_line_edit.setObjectName("massa_oksidov_zheleza_line_edit")
        self.poteri_metalla_s_vynosami_i_vybrosami_line_edit = QtWidgets.QLineEdit(self.rashodnaya_chast_group_box)
        self.poteri_metalla_s_vynosami_i_vybrosami_line_edit.setEnabled(False)
        self.poteri_metalla_s_vynosami_i_vybrosami_line_edit.setGeometry(QtCore.QRect(270, 70, 101, 20))
        self.poteri_metalla_s_vynosami_i_vybrosami_line_edit.setObjectName(
            "poteri_metalla_s_vynosami_i_vybrosami_line_edit")
        self.poteri_zheleza_s_pylyu_line_edit = QtWidgets.QLineEdit(self.rashodnaya_chast_group_box)
        self.poteri_zheleza_s_pylyu_line_edit.setEnabled(False)
        self.poteri_zheleza_s_pylyu_line_edit.setGeometry(QtCore.QRect(270, 90, 101, 20))
        self.poteri_zheleza_s_pylyu_line_edit.setObjectName("poteri_zheleza_s_pylyu_line_edit")
        self.rashodnaya_chast_table_widget = QtWidgets.QTableWidget(self.rashodnaya_chast_group_box)
        self.rashodnaya_chast_table_widget.setEnabled(False)
        self.rashodnaya_chast_table_widget.setGeometry(QtCore.QRect(20, 120, 441, 241))
        self.rashodnaya_chast_table_widget.setObjectName("rashodnaya_chast_table_widget")
        self.rashodnaya_chast_table_widget.setColumnCount(3)
        self.rashodnaya_chast_table_widget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnaya_chast_table_widget.setHorizontalHeaderItem(2, item)
        self.NextTerm = QtWidgets.QLabel(self.tab_3)
        self.NextTerm.setEnabled(False)
        self.NextTerm.setGeometry(QtCore.QRect(950, 540, 61, 61))
        self.NextTerm.setText("")
        self.NextTerm.setPixmap(QtGui.QPixmap(":/icons/icons/arrow_right.ico"))
        self.NextTerm.setScaledContents(True)
        self.NextTerm.setObjectName("NextTerm")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.temperatura_zhidkovo_metalla_v_konce_produvki_label_2 = QtWidgets.QLabel(self.tab_4)
        self.temperatura_zhidkovo_metalla_v_konce_produvki_label_2.setGeometry(QtCore.QRect(0, 410, 291, 16))
        self.temperatura_zhidkovo_metalla_v_konce_produvki_label_2.setObjectName(
            "temperatura_zhidkovo_metalla_v_konce_produvki_label_2")
        self.label_49 = QtWidgets.QLabel(self.tab_4)
        self.label_49.setGeometry(QtCore.QRect(290, 540, 201, 16))
        self.label_49.setObjectName("label_49")
        self.rashodnie_statii_group_box_2 = QtWidgets.QGroupBox(self.tab_4)
        self.rashodnie_statii_group_box_2.setGeometry(QtCore.QRect(490, 10, 471, 531))
        self.rashodnie_statii_group_box_2.setObjectName("rashodnie_statii_group_box_2")
        self.zatrati_tepla_na_pileobrazovanie_line_edit_2 = QtWidgets.QLineEdit(self.rashodnie_statii_group_box_2)
        self.zatrati_tepla_na_pileobrazovanie_line_edit_2.setEnabled(False)
        self.zatrati_tepla_na_pileobrazovanie_line_edit_2.setGeometry(QtCore.QRect(300, 120, 101, 20))
        self.zatrati_tepla_na_pileobrazovanie_line_edit_2.setObjectName("zatrati_tepla_na_pileobrazovanie_line_edit_2")
        self.phizicheskoe_teplo_shlaka_line_edit_2 = QtWidgets.QLineEdit(self.rashodnie_statii_group_box_2)
        self.phizicheskoe_teplo_shlaka_line_edit_2.setEnabled(False)
        self.phizicheskoe_teplo_shlaka_line_edit_2.setGeometry(QtCore.QRect(300, 40, 101, 20))
        self.phizicheskoe_teplo_shlaka_line_edit_2.setObjectName("phizicheskoe_teplo_shlaka_line_edit_2")
        self.phizicheskoe_teplo_zhidkovo_metalla_label_2 = QtWidgets.QLabel(self.rashodnie_statii_group_box_2)
        self.phizicheskoe_teplo_zhidkovo_metalla_label_2.setGeometry(QtCore.QRect(20, 20, 221, 16))
        self.phizicheskoe_teplo_zhidkovo_metalla_label_2.setObjectName("phizicheskoe_teplo_zhidkovo_metalla_label_2")
        self.phizicheskoe_teplo_zhidkovo_metalla_line_edit_2 = QtWidgets.QLineEdit(self.rashodnie_statii_group_box_2)
        self.phizicheskoe_teplo_zhidkovo_metalla_line_edit_2.setEnabled(False)
        self.phizicheskoe_teplo_zhidkovo_metalla_line_edit_2.setGeometry(QtCore.QRect(300, 20, 101, 20))
        self.phizicheskoe_teplo_zhidkovo_metalla_line_edit_2.setObjectName(
            "phizicheskoe_teplo_zhidkovo_metalla_line_edit_2")
        self.poteri_tepla_s_vynosami_i_vybrosami_line_edit_2 = QtWidgets.QLineEdit(self.rashodnie_statii_group_box_2)
        self.poteri_tepla_s_vynosami_i_vybrosami_line_edit_2.setEnabled(False)
        self.poteri_tepla_s_vynosami_i_vybrosami_line_edit_2.setGeometry(QtCore.QRect(300, 100, 101, 20))
        self.poteri_tepla_s_vynosami_i_vybrosami_line_edit_2.setObjectName(
            "poteri_tepla_s_vynosami_i_vybrosami_line_edit_2")
        self.zatrati_tepla_na_razlozhenie_oksidov_zheleza_label_2 = QtWidgets.QLabel(self.rashodnie_statii_group_box_2)
        self.zatrati_tepla_na_razlozhenie_oksidov_zheleza_label_2.setGeometry(QtCore.QRect(20, 80, 281, 16))
        self.zatrati_tepla_na_razlozhenie_oksidov_zheleza_label_2.setObjectName(
            "zatrati_tepla_na_razlozhenie_oksidov_zheleza_label_2")
        self.poteri_tepla_s_vynosami_i_vybrosami_label_2 = QtWidgets.QLabel(self.rashodnie_statii_group_box_2)
        self.poteri_tepla_s_vynosami_i_vybrosami_label_2.setGeometry(QtCore.QRect(20, 100, 251, 16))
        self.poteri_tepla_s_vynosami_i_vybrosami_label_2.setObjectName("poteri_tepla_s_vynosami_i_vybrosami_label_2")
        self.zatrati_tepla_na_pileobrazovanie_label_2 = QtWidgets.QLabel(self.rashodnie_statii_group_box_2)
        self.zatrati_tepla_na_pileobrazovanie_label_2.setGeometry(QtCore.QRect(20, 120, 251, 16))
        self.zatrati_tepla_na_pileobrazovanie_label_2.setObjectName("zatrati_tepla_na_pileobrazovanie_label_2")
        self.phizicheskoe_teplo_othodyashih_gazov_label_2 = QtWidgets.QLabel(self.rashodnie_statii_group_box_2)
        self.phizicheskoe_teplo_othodyashih_gazov_label_2.setGeometry(QtCore.QRect(20, 60, 261, 16))
        self.phizicheskoe_teplo_othodyashih_gazov_label_2.setObjectName("phizicheskoe_teplo_othodyashih_gazov_label_2")
        self.phizicheskoe_teplo_othodyashih_gazov_line_edit_2 = QtWidgets.QLineEdit(self.rashodnie_statii_group_box_2)
        self.phizicheskoe_teplo_othodyashih_gazov_line_edit_2.setEnabled(False)
        self.phizicheskoe_teplo_othodyashih_gazov_line_edit_2.setGeometry(QtCore.QRect(300, 60, 101, 20))
        self.phizicheskoe_teplo_othodyashih_gazov_line_edit_2.setObjectName(
            "phizicheskoe_teplo_othodyashih_gazov_line_edit_2")
        self.phizicheskoe_teplo_shlaka_label_2 = QtWidgets.QLabel(self.rashodnie_statii_group_box_2)
        self.phizicheskoe_teplo_shlaka_label_2.setGeometry(QtCore.QRect(20, 40, 251, 16))
        self.phizicheskoe_teplo_shlaka_label_2.setObjectName("phizicheskoe_teplo_shlaka_label_2")
        self.zatrati_tepla_na_razlozhenie_oksidov_zheleza_line_edit_2 = QtWidgets.QLineEdit(
            self.rashodnie_statii_group_box_2)
        self.zatrati_tepla_na_razlozhenie_oksidov_zheleza_line_edit_2.setEnabled(False)
        self.zatrati_tepla_na_razlozhenie_oksidov_zheleza_line_edit_2.setGeometry(QtCore.QRect(300, 80, 101, 20))
        self.zatrati_tepla_na_razlozhenie_oksidov_zheleza_line_edit_2.setObjectName(
            "zatrati_tepla_na_razlozhenie_oksidov_zheleza_line_edit_2")
        self.teplovie_poteri_line_edit_2 = QtWidgets.QLineEdit(self.rashodnie_statii_group_box_2)
        self.teplovie_poteri_line_edit_2.setEnabled(False)
        self.teplovie_poteri_line_edit_2.setGeometry(QtCore.QRect(300, 160, 101, 20))
        self.teplovie_poteri_line_edit_2.setObjectName("teplovie_poteri_line_edit_2")
        self.teplovie_poteri_label_2 = QtWidgets.QLabel(self.rashodnie_statii_group_box_2)
        self.teplovie_poteri_label_2.setGeometry(QtCore.QRect(20, 160, 251, 16))
        self.teplovie_poteri_label_2.setObjectName("teplovie_poteri_label_2")
        self.teplo_na_razlozhenie_karbonatov_label_2 = QtWidgets.QLabel(self.rashodnie_statii_group_box_2)
        self.teplo_na_razlozhenie_karbonatov_label_2.setGeometry(QtCore.QRect(20, 140, 281, 16))
        self.teplo_na_razlozhenie_karbonatov_label_2.setObjectName("teplo_na_razlozhenie_karbonatov_label_2")
        self.obshii_rashod_tepla_label_2 = QtWidgets.QLabel(self.rashodnie_statii_group_box_2)
        self.obshii_rashod_tepla_label_2.setGeometry(QtCore.QRect(20, 180, 251, 16))
        self.obshii_rashod_tepla_label_2.setObjectName("obshii_rashod_tepla_label_2")
        self.teplo_na_razlozhenie_karbonatov_line_edit_2 = QtWidgets.QLineEdit(self.rashodnie_statii_group_box_2)
        self.teplo_na_razlozhenie_karbonatov_line_edit_2.setEnabled(False)
        self.teplo_na_razlozhenie_karbonatov_line_edit_2.setGeometry(QtCore.QRect(300, 140, 101, 20))
        self.teplo_na_razlozhenie_karbonatov_line_edit_2.setObjectName("teplo_na_razlozhenie_karbonatov_line_edit_2")
        self.obshii_rashod_tepla_line_edit_2 = QtWidgets.QLineEdit(self.rashodnie_statii_group_box_2)
        self.obshii_rashod_tepla_line_edit_2.setEnabled(False)
        self.obshii_rashod_tepla_line_edit_2.setGeometry(QtCore.QRect(300, 180, 101, 20))
        self.obshii_rashod_tepla_line_edit_2.setObjectName("obshii_rashod_tepla_line_edit_2")
        self.rashodnie_statii_table_widget_2 = QtWidgets.QTableWidget(self.rashodnie_statii_group_box_2)
        self.rashodnie_statii_table_widget_2.setEnabled(False)
        self.rashodnie_statii_table_widget_2.setGeometry(QtCore.QRect(10, 210, 451, 311))
        self.rashodnie_statii_table_widget_2.setObjectName("rashodnie_statii_table_widget_2")
        self.rashodnie_statii_table_widget_2.setColumnCount(2)
        self.rashodnie_statii_table_widget_2.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rashodnie_statii_table_widget_2.setHorizontalHeaderItem(1, item)
        self.temperatura_peregreva_label_2 = QtWidgets.QLabel(self.tab_4)
        self.temperatura_peregreva_label_2.setGeometry(QtCore.QRect(0, 430, 251, 16))
        self.temperatura_peregreva_label_2.setObjectName("temperatura_peregreva_label_2")
        self.temperatura_zhidkovo_metalla_v_konce_produvki_line_edit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.temperatura_zhidkovo_metalla_v_konce_produvki_line_edit_2.setEnabled(False)
        self.temperatura_zhidkovo_metalla_v_konce_produvki_line_edit_2.setGeometry(QtCore.QRect(300, 410, 101, 20))
        self.temperatura_zhidkovo_metalla_v_konce_produvki_line_edit_2.setObjectName(
            "temperatura_zhidkovo_metalla_v_konce_produvki_line_edit_2")
        self.prihodnie_statii_group_box_2 = QtWidgets.QGroupBox(self.tab_4)
        self.prihodnie_statii_group_box_2.setGeometry(QtCore.QRect(0, 10, 481, 391))
        self.prihodnie_statii_group_box_2.setObjectName("prihodnie_statii_group_box_2")
        self.himicheskoe_teplo_ot_obrazovaniya_oksidov_line_edit_2 = QtWidgets.QLineEdit(
            self.prihodnie_statii_group_box_2)
        self.himicheskoe_teplo_ot_obrazovaniya_oksidov_line_edit_2.setEnabled(False)
        self.himicheskoe_teplo_ot_obrazovaniya_oksidov_line_edit_2.setGeometry(QtCore.QRect(290, 70, 101, 20))
        self.himicheskoe_teplo_ot_obrazovaniya_oksidov_line_edit_2.setObjectName(
            "himicheskoe_teplo_ot_obrazovaniya_oksidov_line_edit_2")
        self.teplovoi_effect_reakcii_okisleniya_line_edit_2 = QtWidgets.QLineEdit(self.prihodnie_statii_group_box_2)
        self.teplovoi_effect_reakcii_okisleniya_line_edit_2.setEnabled(False)
        self.teplovoi_effect_reakcii_okisleniya_line_edit_2.setGeometry(QtCore.QRect(290, 50, 101, 20))
        self.teplovoi_effect_reakcii_okisleniya_line_edit_2.setObjectName(
            "teplovoi_effect_reakcii_okisleniya_line_edit_2")
        self.teplovoi_effect_reakcii_shlakoobrazovaniya_line_edit_2 = QtWidgets.QLineEdit(
            self.prihodnie_statii_group_box_2)
        self.teplovoi_effect_reakcii_shlakoobrazovaniya_line_edit_2.setEnabled(False)
        self.teplovoi_effect_reakcii_shlakoobrazovaniya_line_edit_2.setGeometry(QtCore.QRect(290, 90, 101, 20))
        self.teplovoi_effect_reakcii_shlakoobrazovaniya_line_edit_2.setObjectName(
            "teplovoi_effect_reakcii_shlakoobrazovaniya_line_edit_2")
        self.teplovoi_effect_reakcii_shlakoobrazovaniya_label_2 = QtWidgets.QLabel(self.prihodnie_statii_group_box_2)
        self.teplovoi_effect_reakcii_shlakoobrazovaniya_label_2.setGeometry(QtCore.QRect(10, 90, 281, 16))
        self.teplovoi_effect_reakcii_shlakoobrazovaniya_label_2.setObjectName(
            "teplovoi_effect_reakcii_shlakoobrazovaniya_label_2")
        self.teplovoi_effect_reakcii_okisleniya_label_2 = QtWidgets.QLabel(self.prihodnie_statii_group_box_2)
        self.teplovoi_effect_reakcii_okisleniya_label_2.setGeometry(QtCore.QRect(10, 50, 251, 16))
        self.teplovoi_effect_reakcii_okisleniya_label_2.setObjectName("teplovoi_effect_reakcii_okisleniya_label_2")
        self.himicheskoe_teplo_ot_obrazovaniya_oksidov_label_2 = QtWidgets.QLabel(self.prihodnie_statii_group_box_2)
        self.himicheskoe_teplo_ot_obrazovaniya_oksidov_label_2.setGeometry(QtCore.QRect(10, 70, 261, 16))
        self.himicheskoe_teplo_ot_obrazovaniya_oksidov_label_2.setObjectName(
            "himicheskoe_teplo_ot_obrazovaniya_oksidov_label_2")
        self.phizicheskoe_teplo_zhidkovo_chuguna_label_2 = QtWidgets.QLabel(self.prihodnie_statii_group_box_2)
        self.phizicheskoe_teplo_zhidkovo_chuguna_label_2.setGeometry(QtCore.QRect(10, 30, 221, 16))
        self.phizicheskoe_teplo_zhidkovo_chuguna_label_2.setObjectName("phizicheskoe_teplo_zhidkovo_chuguna_label_2")
        self.phizicheskoe_teplo_zhidkovo_chuguna_line_edit_2 = QtWidgets.QLineEdit(self.prihodnie_statii_group_box_2)
        self.phizicheskoe_teplo_zhidkovo_chuguna_line_edit_2.setEnabled(False)
        self.phizicheskoe_teplo_zhidkovo_chuguna_line_edit_2.setGeometry(QtCore.QRect(290, 30, 101, 20))
        self.phizicheskoe_teplo_zhidkovo_chuguna_line_edit_2.setObjectName(
            "phizicheskoe_teplo_zhidkovo_chuguna_line_edit_2")
        self.teplo_ot_dozhiganiya_co_line_edit_2 = QtWidgets.QLineEdit(self.prihodnie_statii_group_box_2)
        self.teplo_ot_dozhiganiya_co_line_edit_2.setEnabled(False)
        self.teplo_ot_dozhiganiya_co_line_edit_2.setGeometry(QtCore.QRect(290, 110, 101, 20))
        self.teplo_ot_dozhiganiya_co_line_edit_2.setObjectName("teplo_ot_dozhiganiya_co_line_edit_2")
        self.teplo_ot_dozhiganiya_co_label_2 = QtWidgets.QLabel(self.prihodnie_statii_group_box_2)
        self.teplo_ot_dozhiganiya_co_label_2.setGeometry(QtCore.QRect(10, 110, 251, 16))
        self.teplo_ot_dozhiganiya_co_label_2.setObjectName("teplo_ot_dozhiganiya_co_label_2")
        self.obshii_prihod_tepla_line_edit_2 = QtWidgets.QLineEdit(self.prihodnie_statii_group_box_2)
        self.obshii_prihod_tepla_line_edit_2.setEnabled(False)
        self.obshii_prihod_tepla_line_edit_2.setGeometry(QtCore.QRect(290, 130, 101, 20))
        self.obshii_prihod_tepla_line_edit_2.setObjectName("obshii_prihod_tepla_line_edit_2")
        self.obshii_prihod_tepla_label_2 = QtWidgets.QLabel(self.prihodnie_statii_group_box_2)
        self.obshii_prihod_tepla_label_2.setGeometry(QtCore.QRect(10, 130, 251, 16))
        self.obshii_prihod_tepla_label_2.setObjectName("obshii_prihod_tepla_label_2")
        self.prihodnie_statii_table_widget_2 = QtWidgets.QTableWidget(self.prihodnie_statii_group_box_2)
        self.prihodnie_statii_table_widget_2.setEnabled(False)
        self.prihodnie_statii_table_widget_2.setGeometry(QtCore.QRect(0, 160, 471, 221))
        self.prihodnie_statii_table_widget_2.setObjectName("prihodnie_statii_table_widget_2")
        self.prihodnie_statii_table_widget_2.setColumnCount(2)
        self.prihodnie_statii_table_widget_2.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_statii_table_widget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_statii_table_widget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_statii_table_widget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_statii_table_widget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_statii_table_widget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_statii_table_widget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_statii_table_widget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.prihodnie_statii_table_widget_2.setHorizontalHeaderItem(1, item)
        self.pereiti_k_raschetu_raskisleniya_stali_i_him_sostava_push_button_2 = QtWidgets.QPushButton(self.tab_4)
        self.pereiti_k_raschetu_raskisleniya_stali_i_him_sostava_push_button_2.setEnabled(True)
        self.pereiti_k_raschetu_raskisleniya_stali_i_him_sostava_push_button_2.setGeometry(
            QtCore.QRect(360, 470, 51, 61))
        self.pereiti_k_raschetu_raskisleniya_stali_i_him_sostava_push_button_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/flask_green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pereiti_k_raschetu_raskisleniya_stali_i_him_sostava_push_button_2.setIcon(icon4)
        self.pereiti_k_raschetu_raskisleniya_stali_i_him_sostava_push_button_2.setIconSize(QtCore.QSize(50, 50))
        self.pereiti_k_raschetu_raskisleniya_stali_i_him_sostava_push_button_2.setObjectName(
            "pereiti_k_raschetu_raskisleniya_stali_i_him_sostava_push_button_2")
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_soderzhaniya_ugleroda_v_chugune_push_button_2 = QtWidgets.QPushButton(
            self.tab_4)
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_soderzhaniya_ugleroda_v_chugune_push_button_2.setEnabled(
            True)
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_soderzhaniya_ugleroda_v_chugune_push_button_2.setGeometry(
            QtCore.QRect(230, 470, 51, 61))
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_soderzhaniya_ugleroda_v_chugune_push_button_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/graph1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_soderzhaniya_ugleroda_v_chugune_push_button_2.setIcon(
            icon5)
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_soderzhaniya_ugleroda_v_chugune_push_button_2.setIconSize(
            QtCore.QSize(45, 45))
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_soderzhaniya_ugleroda_v_chugune_push_button_2.setObjectName(
            "pokazat_graphik_zavimisoti_temperatury_plavki_ot_soderzhaniya_ugleroda_v_chugune_push_button_2")
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_temperatury_chuguna_push_button_2 = QtWidgets.QPushButton(
            self.tab_4)
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_temperatury_chuguna_push_button_2.setEnabled(True)
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_temperatury_chuguna_push_button_2.setGeometry(
            QtCore.QRect(170, 470, 51, 61))
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_temperatury_chuguna_push_button_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/graph.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_temperatury_chuguna_push_button_2.setIcon(icon6)
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_temperatury_chuguna_push_button_2.setIconSize(
            QtCore.QSize(45, 45))
        self.pokazat_graphik_zavimisoti_temperatury_plavki_ot_temperatury_chuguna_push_button_2.setObjectName(
            "pokazat_graphik_zavimisoti_temperatury_plavki_ot_temperatury_chuguna_push_button_2")
        self.spravka_o_teplovom_balanse_push_button_2 = QtWidgets.QPushButton(self.tab_4)
        self.spravka_o_teplovom_balanse_push_button_2.setGeometry(QtCore.QRect(50, 470, 51, 61))
        self.spravka_o_teplovom_balanse_push_button_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/help.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.spravka_o_teplovom_balanse_push_button_2.setIcon(icon7)
        self.spravka_o_teplovom_balanse_push_button_2.setIconSize(QtCore.QSize(48, 48))
        self.spravka_o_teplovom_balanse_push_button_2.setObjectName("spravka_o_teplovom_balanse_push_button_2")
        self.temperatura_peregreva_line_edit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.temperatura_peregreva_line_edit_2.setEnabled(False)
        self.temperatura_peregreva_line_edit_2.setGeometry(QtCore.QRect(300, 430, 101, 20))
        self.temperatura_peregreva_line_edit_2.setObjectName("temperatura_peregreva_line_edit_2")
        self.raschet_teplovovo_balansa_push_button_2 = QtWidgets.QPushButton(self.tab_4)
        self.raschet_teplovovo_balansa_push_button_2.setGeometry(QtCore.QRect(110, 470, 51, 61))
        self.raschet_teplovovo_balansa_push_button_2.setText("")
        self.raschet_teplovovo_balansa_push_button_2.setIcon(icon3)
        self.raschet_teplovovo_balansa_push_button_2.setIconSize(QtCore.QSize(48, 48))
        self.raschet_teplovovo_balansa_push_button_2.setObjectName("raschet_teplovovo_balansa_push_button_2")
        self.label_50 = QtWidgets.QLabel(self.tab_4)
        self.label_50.setGeometry(QtCore.QRect(290, 470, 61, 61))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap(":/icons/icons/arrow_right.ico"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.NextSteel = QtWidgets.QLabel(self.tab_4)
        self.NextSteel.setEnabled(False)
        self.NextSteel.setGeometry(QtCore.QRect(940, 540, 61, 61))
        self.NextSteel.setText("")
        self.NextSteel.setPixmap(QtGui.QPixmap(":/icons/icons/arrow_right.ico"))
        self.NextSteel.setScaledContents(True)
        self.NextSteel.setObjectName("NextSteel")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tip_ferrosplava_label_2 = QtWidgets.QLabel(self.tab_5)
        self.tip_ferrosplava_label_2.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.tip_ferrosplava_label_2.setObjectName("tip_ferrosplava_label_2")
        self.vyhod_pervovo_metalla_posle_raskisleniya_line_edit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.vyhod_pervovo_metalla_posle_raskisleniya_line_edit_2.setEnabled(False)
        self.vyhod_pervovo_metalla_posle_raskisleniya_line_edit_2.setGeometry(QtCore.QRect(770, 80, 91, 20))
        self.vyhod_pervovo_metalla_posle_raskisleniya_line_edit_2.setObjectName(
            "vyhod_pervovo_metalla_posle_raskisleniya_line_edit_2")
        self.balans_pri_raskislenii_stali_label_2 = QtWidgets.QLabel(self.tab_5)
        self.balans_pri_raskislenii_stali_label_2.setGeometry(QtCore.QRect(10, 160, 251, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.balans_pri_raskislenii_stali_label_2.setFont(font)
        self.balans_pri_raskislenii_stali_label_2.setObjectName("balans_pri_raskislenii_stali_label_2")
        self.label_51 = QtWidgets.QLabel(self.tab_5)
        self.label_51.setGeometry(QtCore.QRect(770, 60, 211, 16))
        self.label_51.setObjectName("label_51")
        self.vyhod_tretievo_metalla_posle_raskisleniya_line_edit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.vyhod_tretievo_metalla_posle_raskisleniya_line_edit_2.setEnabled(False)
        self.vyhod_tretievo_metalla_posle_raskisleniya_line_edit_2.setGeometry(QtCore.QRect(770, 140, 91, 20))
        self.vyhod_tretievo_metalla_posle_raskisleniya_line_edit_2.setObjectName(
            "vyhod_tretievo_metalla_posle_raskisleniya_line_edit_2")
        self.rashod_tretievo_ferrosplava_line_edit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.rashod_tretievo_ferrosplava_line_edit_2.setEnabled(False)
        self.rashod_tretievo_ferrosplava_line_edit_2.setGeometry(QtCore.QRect(630, 140, 91, 20))
        self.rashod_tretievo_ferrosplava_line_edit_2.setObjectName("rashod_tretievo_ferrosplava_line_edit_2")
        self.raschet_raskisleniya_stali_push_button_2 = QtWidgets.QPushButton(self.tab_5)
        self.raschet_raskisleniya_stali_push_button_2.setGeometry(QtCore.QRect(530, 430, 51, 61))
        self.raschet_raskisleniya_stali_push_button_2.setText("")
        self.raschet_raskisleniya_stali_push_button_2.setIcon(icon3)
        self.raschet_raskisleniya_stali_push_button_2.setIconSize(QtCore.QSize(48, 48))
        self.raschet_raskisleniya_stali_push_button_2.setObjectName("raschet_raskisleniya_stali_push_button_2")
        self.vyhod_vtorovo_metalla_posle_raskisleniya_line_edit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.vyhod_vtorovo_metalla_posle_raskisleniya_line_edit_2.setEnabled(False)
        self.vyhod_vtorovo_metalla_posle_raskisleniya_line_edit_2.setGeometry(QtCore.QRect(770, 110, 91, 20))
        self.vyhod_vtorovo_metalla_posle_raskisleniya_line_edit_2.setObjectName(
            "vyhod_vtorovo_metalla_posle_raskisleniya_line_edit_2")
        self.tip_ferrosplava_combo_box_2 = QtWidgets.QComboBox(self.tab_5)
        self.tip_ferrosplava_combo_box_2.setGeometry(QtCore.QRect(110, 10, 161, 22))
        self.tip_ferrosplava_combo_box_2.setEditable(False)
        self.tip_ferrosplava_combo_box_2.setObjectName("tip_ferrosplava_combo_box_2")
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2 = QtWidgets.QTableWidget(self.tab_5)
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setEnabled(False)
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setGeometry(QtCore.QRect(10, 430, 511, 61))
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setObjectName(
            "himicheskii_sostav_poluchennoi_stali_table_widget_2")
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setColumnCount(5)
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_poluchennoi_stali_table_widget_2.setHorizontalHeaderItem(4, item)
        self.himicheskii_sostav_poluchennoi_stali_label_2 = QtWidgets.QLabel(self.tab_5)
        self.himicheskii_sostav_poluchennoi_stali_label_2.setGeometry(QtCore.QRect(10, 400, 221, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.himicheskii_sostav_poluchennoi_stali_label_2.setFont(font)
        self.himicheskii_sostav_poluchennoi_stali_label_2.setObjectName("himicheskii_sostav_poluchennoi_stali_label_2")
        self.dobavit_ferrosplav_push_button_2 = QtWidgets.QPushButton(self.tab_5)
        self.dobavit_ferrosplav_push_button_2.setGeometry(QtCore.QRect(280, 10, 41, 23))
        self.dobavit_ferrosplav_push_button_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dobavit_ferrosplav_push_button_2.setIcon(icon8)
        self.dobavit_ferrosplav_push_button_2.setObjectName("dobavit_ferrosplav_push_button_2")
        self.label_52 = QtWidgets.QLabel(self.tab_5)
        self.label_52.setGeometry(QtCore.QRect(630, 60, 141, 16))
        self.label_52.setObjectName("label_52")
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2 = QtWidgets.QTableWidget(self.tab_5)
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setEnabled(True)
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setGeometry(QtCore.QRect(10, 60, 611, 91))
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setObjectName(
            "himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2")
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setColumnCount(6)
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.setHorizontalHeaderItem(5, item)
        self.balans_pri_raskislenii_stali_line_edit_2 = QtWidgets.QTableWidget(self.tab_5)
        self.balans_pri_raskislenii_stali_line_edit_2.setEnabled(True)
        self.balans_pri_raskislenii_stali_line_edit_2.setGeometry(QtCore.QRect(10, 180, 1001, 211))
        self.balans_pri_raskislenii_stali_line_edit_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.balans_pri_raskislenii_stali_line_edit_2.setObjectName("balans_pri_raskislenii_stali_line_edit_2")
        self.balans_pri_raskislenii_stali_line_edit_2.setColumnCount(10)
        self.balans_pri_raskislenii_stali_line_edit_2.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.balans_pri_raskislenii_stali_line_edit_2.setHorizontalHeaderItem(9, item)
        self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeader().setDefaultSectionSize(70)
        self.rashod_vtorovo_ferrosplava_line_edit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.rashod_vtorovo_ferrosplava_line_edit_2.setEnabled(False)
        self.rashod_vtorovo_ferrosplava_line_edit_2.setGeometry(QtCore.QRect(630, 110, 91, 20))
        self.rashod_vtorovo_ferrosplava_line_edit_2.setObjectName("rashod_vtorovo_ferrosplava_line_edit_2")
        self.rashod_pervovo_ferrosplava_line_edit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.rashod_pervovo_ferrosplava_line_edit_2.setEnabled(False)
        self.rashod_pervovo_ferrosplava_line_edit_2.setGeometry(QtCore.QRect(630, 80, 91, 20))
        self.rashod_pervovo_ferrosplava_line_edit_2.setObjectName("rashod_pervovo_ferrosplava_line_edit_2")
        self.udalit_ferrosplav_push_button_2 = QtWidgets.QPushButton(self.tab_5)
        self.udalit_ferrosplav_push_button_2.setGeometry(QtCore.QRect(330, 10, 41, 23))
        self.udalit_ferrosplav_push_button_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/remove.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.udalit_ferrosplav_push_button_2.setIcon(icon9)
        self.udalit_ferrosplav_push_button_2.setObjectName("udalit_ferrosplav_push_button_2")
        self.NextRes = QtWidgets.QLabel(self.tab_5)
        self.NextRes.setEnabled(False)
        self.NextRes.setGeometry(QtCore.QRect(950, 540, 61, 61))
        self.NextRes.setText("")
        self.NextRes.setPixmap(QtGui.QPixmap(":/icons/icons/arrow_right.ico"))
        self.NextRes.setScaledContents(True)
        self.NextRes.setObjectName("NextRes")
        self.tabWidget.addTab(self.tab_5, "")
        OperatorForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OperatorForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 21))
        self.menubar.setObjectName("menubar")
        self.Menu = QtWidgets.QMenu(self.menubar)
        self.Menu.setObjectName("Menu")
        self.Help = QtWidgets.QMenu(self.menubar)
        self.Help.setObjectName("Help")
        self.Administrate = QtWidgets.QMenu(self.menubar)
        self.Administrate.setEnabled(False)
        self.Administrate.setObjectName("Administrate")
        OperatorForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OperatorForm)
        self.statusbar.setObjectName("statusbar")
        OperatorForm.setStatusBar(self.statusbar)
        self.about = QtWidgets.QAction(OperatorForm)
        self.about.setObjectName("about")
        self.OpenFile = QtWidgets.QAction(OperatorForm)
        self.OpenFile.setObjectName("OpenFile")
        self.Exit = QtWidgets.QAction(OperatorForm)
        self.Exit.setObjectName("Exit")
        self.addUser = QtWidgets.QAction(OperatorForm)
        self.addUser.setEnabled(False)
        self.addUser.setObjectName("addUser")
        self.AddUser = QtWidgets.QAction(OperatorForm)
        self.AddUser.setEnabled(True)
        self.AddUser.setObjectName("AddUser")
        self.AddDbData = QtWidgets.QAction(OperatorForm)
        self.AddDbData.setEnabled(True)
        self.AddDbData.setObjectName("AddDbData")
        self.Menu.addAction(self.OpenFile)
        self.Menu.addSeparator()
        self.Menu.addAction(self.Exit)
        self.Help.addAction(self.about)
        self.Administrate.addAction(self.AddUser)
        self.Administrate.addAction(self.AddDbData)
        self.menubar.addAction(self.Menu.menuAction())
        self.menubar.addAction(self.Administrate.menuAction())
        self.menubar.addAction(self.Help.menuAction())

        self.retranslateUi(OperatorForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OperatorForm)

    def retranslateUi(self, OperatorForm):
        _translate = QtCore.QCoreApplication.translate
        OperatorForm.setWindowTitle(_translate("OperatorForm", "MainWindow"))
        self.groupBox.setTitle(_translate("OperatorForm", "Сталь"))
        self.groupBox_4.setTitle(_translate("OperatorForm", "Химический состав"))
        self.label.setText(_translate("OperatorForm", "Углерод (C):"))
        self.label_2.setText(_translate("OperatorForm", "Кремний (Si):"))
        self.label_3.setText(_translate("OperatorForm", "Сера (S):"))
        self.label_4.setText(_translate("OperatorForm", "Фосфор (P):"))
        self.groupBox_2.setTitle(_translate("OperatorForm", "Чугун"))
        self.label_5.setText(_translate("OperatorForm", "Температура (℃):"))
        self.label_6.setText(_translate("OperatorForm", "Масса (Т):"))
        self.groupBox_6.setTitle(_translate("OperatorForm", "Химический состав"))
        self.label_7.setText(_translate("OperatorForm", "Углерод (C):"))
        self.label_8.setText(_translate("OperatorForm", "Кремний (Si):"))
        self.label_9.setText(_translate("OperatorForm", "Сера (S):"))
        self.label_10.setText(_translate("OperatorForm", "Фосфор (P):"))
        self.label_24.setText(_translate("OperatorForm", "Марганец (Mn):"))
        self.groupBox_5.setTitle(_translate("OperatorForm", "Металлошихта"))
        self.label_16.setText(_translate("OperatorForm", "Масса:"))
        self.groupBox_3.setTitle(_translate("OperatorForm", "Лом"))
        self.label_11.setText(_translate("OperatorForm", "Масса (Т):"))
        self.groupBox_7.setTitle(_translate("OperatorForm", "Химический состав"))
        self.label_12.setText(_translate("OperatorForm", "Углерод (C):"))
        self.label_13.setText(_translate("OperatorForm", "Кремний (Si):"))
        self.label_14.setText(_translate("OperatorForm", "Сера (S):"))
        self.label_15.setText(_translate("OperatorForm", "Фосфор (P):"))
        self.label_25.setText(_translate("OperatorForm", "Марганец (Mn):"))
        self.groupBox_8.setTitle(_translate("OperatorForm", "Химический состав"))
        self.label_17.setText(_translate("OperatorForm", "Углерод (C):"))
        self.label_18.setText(_translate("OperatorForm", "Сера (S):"))
        self.label_19.setText(_translate("OperatorForm", "Кремний (Si):"))
        self.label_20.setText(_translate("OperatorForm", "Фосфор (P):"))
        self.label_21.setText(_translate("OperatorForm", "Марганец (Mn):"))
        self.groupBox_9.setTitle(_translate("OperatorForm", "Окисление элементов металлошихты (на 100кг металлошихты)"))
        self.label_22.setText(_translate("OperatorForm", "Масса:"))
        item = self.OxidationTable.verticalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Содержится в шихте"))
        item = self.OxidationTable.verticalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Остаётся после продувки"))
        item = self.OxidationTable.verticalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Удаляется после продувки"))
        item = self.OxidationTable.verticalHeaderItem(3)
        item.setText(_translate("OperatorForm", "Требуется кислорода [кг]"))
        item = self.OxidationTable.verticalHeaderItem(4)
        item.setText(_translate("OperatorForm", "Требуется кислорода [м^3]"))
        item = self.OxidationTable.verticalHeaderItem(5)
        item.setText(_translate("OperatorForm", "Образуется оксидов"))
        item = self.OxidationTable.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Всего C"))
        item = self.OxidationTable.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Ок. C до CO"))
        item = self.OxidationTable.horizontalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Ок. C до CO2"))
        item = self.OxidationTable.horizontalHeaderItem(3)
        item.setText(_translate("OperatorForm", "Si"))
        item = self.OxidationTable.horizontalHeaderItem(4)
        item.setText(_translate("OperatorForm", "Mn"))
        item = self.OxidationTable.horizontalHeaderItem(5)
        item.setText(_translate("OperatorForm", "P"))
        item = self.OxidationTable.horizontalHeaderItem(6)
        item.setText(_translate("OperatorForm", "S"))
        item = self.OxidationTable.horizontalHeaderItem(7)
        item.setText(_translate("OperatorForm", "Всего"))
        __sortingEnabled = self.OxidationTable.isSortingEnabled()
        self.OxidationTable.setSortingEnabled(False)
        self.OxidationTable.setSortingEnabled(__sortingEnabled)
        self.groupBox_11.setTitle(_translate("OperatorForm", "Выбрать режим и параметры из базы данных"))
        self.label_23.setText(_translate("OperatorForm", "Режим:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OperatorForm", "Металлошихта"))
        self.groupBox_10.setTitle(_translate("OperatorForm", "Флюсы"))
        item = self.FluxeTable.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Тип флюса"))
        item = self.FluxeTable.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Масса [т]"))
        self.tip_flyusa_label.setText(_translate("OperatorForm", "Тип флюса:"))
        self.shlak_group_box.setTitle(_translate("OperatorForm", "Шлак"))
        self.him_sostav_shlaka_group_box.setTitle(_translate("OperatorForm", "Химический состав, т"))
        self.SlagSiO2Label.setText(_translate("OperatorForm", "SiO2:"))
        self.SlagCaOLabel.setText(_translate("OperatorForm", "CaO:"))
        self.SlagMgOLabel.setText(_translate("OperatorForm", "MgO:"))
        self.SlagAl2O3Label.setText(_translate("OperatorForm", "Al2O3:"))
        self.SlagOthersLabel.setText(_translate("OperatorForm", "Прочие:"))
        self.SlagFeOLabel.setText(_translate("OperatorForm", "FeO:"))
        self.SlagFe2O3Label.setText(_translate("OperatorForm", "Fe2O3:"))
        self.SlagWeightLabel.setText(_translate("OperatorForm", "Масса [т]:"))
        self.him_sostav_shlaka_v_procentah_group_box.setTitle(_translate("OperatorForm", "Химический состав, %"))
        self.SlagAl2O3Label_2.setText(_translate("OperatorForm", "Al2O3:"))
        self.SlagFeOLabel_2.setText(_translate("OperatorForm", "FeO:"))
        self.SlagFe2O3Label_2.setText(_translate("OperatorForm", "Fe2O3:"))
        self.SlagSiO2Label_2.setText(_translate("OperatorForm", "SiO2:"))
        self.SlagCaOLabel_2.setText(_translate("OperatorForm", "CaO:"))
        self.SlagMgOLabel_2.setText(_translate("OperatorForm", "MgO:"))
        self.SlagOthersLabel_2.setText(_translate("OperatorForm", "Прочие:"))
        self.raschet_dutya_group_box.setTitle(_translate("OperatorForm", "Расчет дутья"))
        self.TotalOxygenDemandBlastLabel.setText(
            _translate("OperatorForm", "Общая потребность в кислороде дутья [кг]:"))
        self.TotalConsumptionOfBlastKgLabel.setText(_translate("OperatorForm", "Общий расход дутья [кг]:"))
        self.ExcessBlastLabel.setText(_translate("OperatorForm", "Избыток дутья [кг]:"))
        self.TotalConsumptionOfBlastM3Label.setText(_translate("OperatorForm", "Общий расход дутья [м^3]:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OperatorForm", "Шлак"))
        self.ReclaimedIronWeightLabel.setText(
            _translate("OperatorForm", "Кол-во железа, восстановленного из неметаллических материалов [т]:"))
        item = self.prihodnie_dannye_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Наименование"))
        item = self.prihodnie_dannye_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "кг"))
        item = self.rashodnie_dannye_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Наименование"))
        item = self.rashodnie_dannye_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "кг"))
        self.vyhod_zhidkovo_metalla_pered_raskisleniem_label.setText(
            _translate("OperatorForm", "Выход жидкого металла перед раскислением [т]:"))
        self.rashodnaya_chast_group_box.setTitle(_translate("OperatorForm", "Расходная часть"))
        self.massa_okislivshihsya_primesei_label.setText(_translate("OperatorForm", "Масса окислившихся примесей [т]:"))
        self.massa_oksidov_zheleza_label.setText(
            _translate("OperatorForm", "Масса оксидов железа, переходящих в шлак [т]:"))
        self.poteri_metalla_s_vynosami_i_vybrosami_label.setText(
            _translate("OperatorForm", "Потери металла с выносами и выбросами [т]:"))
        self.poteri_zheleza_s_pylyu_label.setText(_translate("OperatorForm", "Потери железа с пылью [т]:"))
        item = self.rashodnaya_chast_table_widget.verticalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Окисление углерода"))
        item = self.rashodnaya_chast_table_widget.verticalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Разложение CaCO3"))
        item = self.rashodnaya_chast_table_widget.verticalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Дожигание части CO"))
        item = self.rashodnaya_chast_table_widget.verticalHeaderItem(3)
        item.setText(_translate("OperatorForm", "Разложение MgCO3"))
        item = self.rashodnaya_chast_table_widget.verticalHeaderItem(4)
        item.setText(_translate("OperatorForm", "Итого, кг"))
        item = self.rashodnaya_chast_table_widget.verticalHeaderItem(5)
        item.setText(_translate("OperatorForm", "Итого, м^3"))
        item = self.rashodnaya_chast_table_widget.verticalHeaderItem(6)
        item.setText(_translate("OperatorForm", "Состав газа, %"))
        item = self.rashodnaya_chast_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "CO"))
        item = self.rashodnaya_chast_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "CO2"))
        item = self.rashodnaya_chast_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Всего"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("OperatorForm", "Материальный баланс"))
        self.temperatura_zhidkovo_metalla_v_konce_produvki_label_2.setText(
            _translate("OperatorForm", "Температура жидкого металла в конце продувки [°C]:"))
        self.label_49.setText(_translate("OperatorForm", "Перейти к расчёту раскисления стали"))
        self.rashodnie_statii_group_box_2.setTitle(_translate("OperatorForm", "Расходные статьи"))
        self.phizicheskoe_teplo_zhidkovo_metalla_label_2.setText(
            _translate("OperatorForm", "Физическое тепло жидкого металла [кДж]:"))
        self.zatrati_tepla_na_razlozhenie_oksidov_zheleza_label_2.setText(
            _translate("OperatorForm", "Затраты тепла на разложение оксидов железа [кДж]:"))
        self.poteri_tepla_s_vynosami_i_vybrosami_label_2.setText(
            _translate("OperatorForm", "Потери тепла с выносами и выбросами [кДж]:"))
        self.zatrati_tepla_na_pileobrazovanie_label_2.setText(
            _translate("OperatorForm", "Затраты тепла на пылеобразование [кДж]:"))
        self.phizicheskoe_teplo_othodyashih_gazov_label_2.setText(
            _translate("OperatorForm", "Физическое тепло отходящих газов [кДж]:"))
        self.phizicheskoe_teplo_shlaka_label_2.setText(_translate("OperatorForm", "Физическое тепло шлака [кДж]:"))
        self.teplovie_poteri_label_2.setText(_translate("OperatorForm", "Тепловые потери [кДж]:"))
        self.teplo_na_razlozhenie_karbonatov_label_2.setText(
            _translate("OperatorForm", "Тепло на разложение карбонатов [кДж]:"))
        self.obshii_rashod_tepla_label_2.setText(_translate("OperatorForm", "Общий расход тепла [кДж]:"))
        item = self.rashodnie_statii_table_widget_2.verticalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Физ. тепло жидкого металла"))
        item = self.rashodnie_statii_table_widget_2.verticalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Физ. тепло шлака"))
        item = self.rashodnie_statii_table_widget_2.verticalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Затраты тепла на разл. оксидов железа"))
        item = self.rashodnie_statii_table_widget_2.verticalHeaderItem(3)
        item.setText(_translate("OperatorForm", "Физ. тепло отходящих газов"))
        item = self.rashodnie_statii_table_widget_2.verticalHeaderItem(4)
        item.setText(_translate("OperatorForm", "Потери тепла с выносами и выбросами"))
        item = self.rashodnie_statii_table_widget_2.verticalHeaderItem(5)
        item.setText(_translate("OperatorForm", "Затраты тепла на пылеобразование"))
        item = self.rashodnie_statii_table_widget_2.verticalHeaderItem(6)
        item.setText(_translate("OperatorForm", "Тепло на разложение карбонатов"))
        item = self.rashodnie_statii_table_widget_2.verticalHeaderItem(7)
        item.setText(_translate("OperatorForm", "Тепловые потери"))
        item = self.rashodnie_statii_table_widget_2.verticalHeaderItem(8)
        item.setText(_translate("OperatorForm", "Итого"))
        item = self.rashodnie_statii_table_widget_2.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Кол-во, кДж"))
        item = self.rashodnie_statii_table_widget_2.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Кол-во, %"))
        self.temperatura_peregreva_label_2.setText(_translate("OperatorForm", "Температура перегрева [°C]:"))
        self.prihodnie_statii_group_box_2.setTitle(_translate("OperatorForm", "Приходные статьи"))
        self.teplovoi_effect_reakcii_shlakoobrazovaniya_label_2.setText(
            _translate("OperatorForm", "Тепловой эффект реакций шлакообразования [кДж]:"))
        self.teplovoi_effect_reakcii_okisleniya_label_2.setText(
            _translate("OperatorForm", "Тепловой эффект реакции окисления [кДж]:"))
        self.himicheskoe_teplo_ot_obrazovaniya_oksidov_label_2.setText(
            _translate("OperatorForm", "Химическое тепло от образования оксидов [кДж]:"))
        self.phizicheskoe_teplo_zhidkovo_chuguna_label_2.setText(
            _translate("OperatorForm", "Физическое тепло жидкого чугуна [кДж]:"))
        self.teplo_ot_dozhiganiya_co_label_2.setText(_translate("OperatorForm", "Тепло от дожигания CO [кДж]:"))
        self.obshii_prihod_tepla_label_2.setText(_translate("OperatorForm", "Общий приход тепла [кДж]:"))
        item = self.prihodnie_statii_table_widget_2.verticalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Физ. тепло жидкого чугуна"))
        item = self.prihodnie_statii_table_widget_2.verticalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Тепл. эффект реакции оксиления"))
        item = self.prihodnie_statii_table_widget_2.verticalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Хим. тепло обр. оксидов железа шлака"))
        item = self.prihodnie_statii_table_widget_2.verticalHeaderItem(3)
        item.setText(_translate("OperatorForm", "Тепл. эффект реакции шлакообразования"))
        item = self.prihodnie_statii_table_widget_2.verticalHeaderItem(4)
        item.setText(_translate("OperatorForm", "Тепло от дожигания CO"))
        item = self.prihodnie_statii_table_widget_2.verticalHeaderItem(5)
        item.setText(_translate("OperatorForm", "Итого"))
        item = self.prihodnie_statii_table_widget_2.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Кол-во, кДж"))
        item = self.prihodnie_statii_table_widget_2.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Кол-во, %"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("OperatorForm", "Тепловой баланс"))
        self.tip_ferrosplava_label_2.setText(_translate("OperatorForm", "Тип ферросллава:"))
        self.balans_pri_raskislenii_stali_label_2.setText(
            _translate("OperatorForm", "Баланс элементов при раскислении стали"))
        self.label_51.setText(_translate("OperatorForm", "Выход металла после раскисления [кг]:"))
        item = self.himicheskii_sostav_poluchennoi_stali_table_widget_2.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "C"))
        item = self.himicheskii_sostav_poluchennoi_stali_table_widget_2.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Si"))
        item = self.himicheskii_sostav_poluchennoi_stali_table_widget_2.horizontalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Mn"))
        item = self.himicheskii_sostav_poluchennoi_stali_table_widget_2.horizontalHeaderItem(3)
        item.setText(_translate("OperatorForm", "S"))
        item = self.himicheskii_sostav_poluchennoi_stali_table_widget_2.horizontalHeaderItem(4)
        item.setText(_translate("OperatorForm", "P"))
        self.himicheskii_sostav_poluchennoi_stali_label_2.setText(
            _translate("OperatorForm", "Химический состав полученной стали"))
        self.label_52.setText(_translate("OperatorForm", "Расход ферросплава [кг]:"))
        item = self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Тип"))
        item = self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "C, %"))
        item = self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.horizontalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Si, %"))
        item = self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.horizontalHeaderItem(3)
        item.setText(_translate("OperatorForm", "Mn, %"))
        item = self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.horizontalHeaderItem(4)
        item.setText(_translate("OperatorForm", "P, %"))
        item = self.himicheskii_sostav_vybrannyh_raskislitelei_table_widget_2.horizontalHeaderItem(5)
        item.setText(_translate("OperatorForm", "S, %"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.verticalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Содержится перед раскислением, %"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.verticalHeaderItem(1)
        item.setText(_translate("OperatorForm", "Содержится перед раскислением, кг"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.verticalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Вносится первым ферросплавом, кг"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.verticalHeaderItem(3)
        item.setText(_translate("OperatorForm", "Содержится после раскисления, кг"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.verticalHeaderItem(4)
        item.setText(_translate("OperatorForm", "Образуется оксида, кг"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.verticalHeaderItem(5)
        item.setText(_translate("OperatorForm", "Состав стали после раск. 1-ым ферросплавом, %"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(0)
        item.setText(_translate("OperatorForm", "Ост. C"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(1)
        item.setText(_translate("OperatorForm", "C до CO"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(2)
        item.setText(_translate("OperatorForm", "Ост. Si"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(3)
        item.setText(_translate("OperatorForm", "Si до SiO2"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(4)
        item.setText(_translate("OperatorForm", "Ост. Mn"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(5)
        item.setText(_translate("OperatorForm", "Mn до MnO"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(6)
        item.setText(_translate("OperatorForm", "P"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(7)
        item.setText(_translate("OperatorForm", "S"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(8)
        item.setText(_translate("OperatorForm", "Fe"))
        item = self.balans_pri_raskislenii_stali_line_edit_2.horizontalHeaderItem(9)
        item.setText(_translate("OperatorForm", "Всего"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("OperatorForm", "Раскисление стали"))
        self.Menu.setTitle(_translate("OperatorForm", "Файл"))
        self.Help.setTitle(_translate("OperatorForm", "Справка"))
        self.Administrate.setTitle(_translate("OperatorForm", "Администрирование"))
        self.about.setText(_translate("OperatorForm", "О программе"))
        self.OpenFile.setText(_translate("OperatorForm", "Открыть"))
        self.Exit.setText(_translate("OperatorForm", "Выйти"))
        self.addUser.setText(_translate("OperatorForm", "Добавить пользователя"))
        self.AddUser.setText(_translate("OperatorForm", "Добавить пользователя"))
        self.AddDbData.setText(_translate("OperatorForm", "Добавить данные в бд"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    OperatorForm = QtWidgets.QMainWindow()
    ui = Ui_OperatorForm()
    ui.setupUi(OperatorForm)
    OperatorForm.show()
    sys.exit(app.exec_())
